---
title: "BBALLFINAL"
author: "Charley Levy"
date: "12/12/2019"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
install.packages("SpatialBall")
library(SpatialBall)
data("season2017")
```


```{r}

BBALL<-read.csv("dat.csv")
str(BBALL)
BBALL$relativeRest[BBALL$relativeRest<=-2]= "-2"
BBALL$relativeRest[BBALL$relativeRest>=2]="2"
str(BBALL)

BBALL1<-table(BBALL$relativeRest, BBALL$ACTION_TYPE)
BBALL1<-data.frame(BBALL1)


BBALL1=BBALL1 %>% 
  rename(
    Relative_Days_Rest= Var1,
    Type_Of_Shot=Var2
    )

# Convert one variable to numeric
BBALL1$Relative_Days_Rest <- as.numeric(as.character(BBALL1$Relative_Days_Rest))  





#stacked bar chart(type of shot by relative days rest
#would like a better color palatte to represent the CATEGORICAL DATA

ggplot(BBALL1, aes(Relative_Days_Rest)) + 
  geom_bar(aes(fill =Type_Of_Shot), position = 'fill')+
  ggtitle("Frequency of each type of shot by relative days of rest")+
  scale_color_brewer(palette="Dark2")


```
```{r}

BBALL2<-table(BBALL$relativeRest, BBALL$SHOT_ZONE_BASIC)
BBALL2<-data.frame(BBALL2)



BBALL2=BBALL2 %>% 
  rename(
    Relative_Days_Rest= Var1,
    Shot_Zone=Var2
    )

# Convert one variable to numeric
BBALL2$Relative_Days_Rest <- as.numeric(as.character(BBALL2$Relative_Days_Rest))  





#stacked bar chart(type of shot by relative days rest
#would like a better color palatte to represent the CATEGORICAL DATA

ggplot(BBALL2, aes(Relative_Days_Rest)) + 
  geom_bar(aes(fill =Shot_Zone), position = 'fill')+
  ggtitle("Relative Frequency of shots in each zone by relative days of rest")+
  scale_color_brewer(palette="Dark2")








```
```{r}


BBALL3<-table(BBALL$relativeRest, BBALL$SHOT_ZONE_RANGE)
BBALL3<-data.frame(BBALL3)



BBALL3=BBALL3 %>% 
  rename(
    Relative_Days_Rest= Var1,
    Shot_Range=Var2
    )

# Convert one variable to numeric
BBALL3$Relative_Days_Rest <- as.numeric(as.character(BBALL3$Relative_Days_Rest))  





#stacked bar chart(type of shot by relative days rest
#would like a better color palatte to represent the CATEGORICAL DATA

ggplot(BBALL3, aes(Relative_Days_Rest)) + 
  geom_bar(aes(fill =Shot_Range), position = 'fill')+
  ggtitle("Relative Frequency of shots in each range by relative days of rest")+
  scale_color_brewer(palette="Dark2")



```

