---
title: "EDAV Fall 2019 PSet 5, part A"
author: "Alex Wan, Junyang Jiang, Charley Levy, Swapnav Deka"
output:
  pdf_document: default
  html_document:
    df_print: paged
---
```{r, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = TRUE)
```

```{r}
library(ggplot2)
library(rjson)
library(grid)
library(jpeg)
library(RCurl)
library(plyr)
library(SpatialBall)
library(dplyr)
data("season2017")
df <- read.csv("dat.csv")
df <- na.omit(df)
team <- unique(df['TEAM_NAME'])
```

```{r}
df$offType = df$teamDayOff
df$offType[df$teamDayOff >= 3]  = "3+"

df$relativeOff = df$teamDayOff - df$opptDayOff
df$relativeOff[df$relativeOff <= -2]  = "-2-"
df$relativeOff[df$relativeOff >= 2]  = "2+"
```


Shot chart for 0,1,2,3+ days of rest for entire league
```{r}
courtImg.URL <- "https://thedatagame.files.wordpress.com/2016/03/nba_court.jpg"
court <- rasterGrob(readJPEG(getURLContent(courtImg.URL)),
                    width=unit(1,"npc"), height=unit(1,"npc"))

ggplot(df, aes(x=LOC_X, y=LOC_Y)) +
  annotation_custom(court, -250, 250, -50, 420)+
  geom_point(aes(colour = SHOT_ZONE_BASIC, shape=EVENT_TYPE, alpha=0.1, stroke=0))+
  facet_wrap(~ offType)
```

Accuracy Charts by Day Off

```{r, fig.height=6, fig.width=12}
dfwoBack <- filter(df, SHOT_ZONE_BASIC != "Backcourt")
off <- c("0", "1", "2", "3+")
for(i in off) {
    p <- ggplot(dfwoBack[dfwoBack$offType == i,], aes(x=LOC_X, y=LOC_Y)) +
      annotation_custom(court, -250, 250, -50, 420)+
      geom_point(aes(colour = SHOT_ZONE_BASIC, shape=EVENT_TYPE, alpha=1/250, stroke=0)) +
      ggtitle(paste("Shot Accuracy Charts with", i, "Days Off"))
    print(p)
}

```



Accuracy Charts by Day Off
```{r}
off <- c("0", "1", "2", "3+")
for(i in off) {
    shotS <- ddply(df[df$offType == i, ], .(SHOT_ZONE_BASIC), summarize, 
                   SHOTS_ATTEMPTED = length(SHOT_MADE_FLAG),
                   SHOTS_MADE = sum(as.numeric(as.character(SHOT_MADE_FLAG))),
                   MLOC_X = mean(LOC_X),
                   MLOC_Y = mean(LOC_Y))
    shotS$SHOT_ACCURACY <- (shotS$SHOTS_MADE / shotS$SHOTS_ATTEMPTED)
    shotS$SHOT_ACCURACY_LAB <- paste(as.character(round(100 * shotS$SHOT_ACCURACY, 1)), "%", sep="") 

    p <- ggplot(shotS, aes(x=MLOC_X, y=MLOC_Y)) + 
      annotation_custom(court, -250, 250, -52, 418) +
      geom_point(aes(colour = SHOT_ZONE_BASIC, size = SHOT_ACCURACY, alpha = 0.8), size = 8) +
      geom_text(aes(colour = SHOT_ZONE_BASIC, label = SHOT_ACCURACY_LAB), vjust = -1.2, size = 3) +
      ggtitle(paste("Shot Accuracy Charts with", i, "Days Off"))
    print(p)
}
```

Draw in a single figure
```{r}
shotS <- ddply(df, .(SHOT_ZONE_BASIC, offType), summarize, 
                   SHOTS_ATTEMPTED = length(SHOT_MADE_FLAG),
                   SHOTS_MADE = sum(as.numeric(as.character(SHOT_MADE_FLAG))),
                   MLOC_X = mean(LOC_X),
                   MLOC_Y = mean(LOC_Y))
shotS$SHOT_ACCURACY <- (shotS$SHOTS_MADE / shotS$SHOTS_ATTEMPTED)
shotS$SHOT_ACCURACY_LAB <- paste(as.character(round(100 * shotS$SHOT_ACCURACY, 1)), "%", sep="") 

ggplot(shotS, aes(x=MLOC_X, y=MLOC_Y)) + 
      annotation_custom(court, -250, 250, -52, 418) +
      geom_point(aes(colour = SHOT_ZONE_BASIC, size = SHOT_ACCURACY, alpha = 0.8), size = 8) +
    
      geom_text(aes(colour = SHOT_ZONE_BASIC, label = SHOT_ACCURACY_LAB), vjust = -1.2, size = 3) +
      facet_wrap(~ offType)
```

But I think Line Chart may be better for shot accuracy:
```{r}
ggplot(shotS, aes(x=offType, y=SHOT_ACCURACY_LAB, group=SHOT_ZONE_BASIC)) + 
  geom_line(aes(color=SHOT_ZONE_BASIC))+
  geom_point(aes(color=SHOT_ZONE_BASIC))
```


Accuracy Charts by relative Day Off
```{r}
off <- c("-2-", "-1", "0", "1", "2+")
for(i in off) {
    shotS <- ddply(df[df$relativeOff == i, ], .(SHOT_ZONE_BASIC), summarize, 
                   SHOTS_ATTEMPTED = length(SHOT_MADE_FLAG),
                   SHOTS_MADE = sum(as.numeric(as.character(SHOT_MADE_FLAG))),
                   MLOC_X = mean(LOC_X),
                   MLOC_Y = mean(LOC_Y))
    shotS$SHOT_ACCURACY <- (shotS$SHOTS_MADE / shotS$SHOTS_ATTEMPTED)
    shotS$SHOT_ACCURACY_LAB <- paste(as.character(round(100 * shotS$SHOT_ACCURACY, 1)), "%", sep="") 

    p <- ggplot(shotS, aes(x=MLOC_X, y=MLOC_Y)) + 
      annotation_custom(court, -250, 250, -52, 418) +
      geom_point(aes(colour = SHOT_ZONE_BASIC, size = SHOT_ACCURACY, alpha = 0.8), size = 8) +
      geom_text(aes(colour = SHOT_ZONE_BASIC, label = SHOT_ACCURACY_LAB), vjust = -1.2, size = 3) +
      ggtitle(paste("Shot Accuracy Charts with", i, "Relative Days Off"))
    print(p)
}
```


Distribution of type of  shots taken for different days rest
```{r}
ggplot(df, aes(x=SHOT_ZONE_BASIC, fill=EVENT_TYPE)) + 
  geom_bar(aes(y = (..count..))) +
  facet_wrap(~ offType) +
  coord_flip()
```


```{r}
x <- df[c("GAME_ID", "teamRslt", "relativeOff")]
x <- x[!duplicated(x),]

winProp=data.frame(prop.table(table(x$relativeOff,x$teamRslt),1))
winProp$Var1 = factor(winProp$Var1, levels=c('-2-','-1','0','1','2+'))
ggplot(winProp,aes(Var1))+
  geom_bar(aes(fill=Var2,y=Freq), position=position_stack(), stat = "identity")+
  coord_flip()+
  labs(y = "Game Result",
       x = "Relative Day Off")
```


